<?
set_include_path('../../include'); 
$page = 'past'; 
$level = 2;
$sub = 2008;
include 'header.php' 
?>
<div class="wrapper col4">
  <div id="container">
  <h2>2008 <i>Beijing Fellowship</i> Blogs Archive- Eric Chiang</h2>
    <div id="content">
     <div id="comments">
        <ul class="commentlist">
          <li class="comment_even">
            <div class="submitdate"><a href="#">Sunday, August 3, 2008</a></div>
            <p>This morning, we arose earlier and went to the Palace Museum (故宮) and Tiananmen Square, which was much larger than I thought. For some reason, I had always mistakenly thought that Tiananmen Square was the size of, say, Bryant Park in New York City. For reference, Bryant Park is about 9.6 acres, while Tiananmen Square, I later discovered, is about 100 acres. From Tiananmen Square, I saw the Great Hall of the People (人民大會堂), and as I soon as I saw Mao Zedong's portrait hanging on the red walls of the great hall, I thought to myself, "百聞不如一見", which basically means "Seeing is believing." At the same time, I noticed a very imposing police officer dressed in blue (about 6'4" or so) standing before the bridge leading up to the Forbidden City, and the only word that came to my cynical mind was "crackdown".
			Yet, that thought abated as soon as I entered the Forbidden City, which seemed absolutely huge to me. In fact, I later realized that the entire city was huge, far larger and far more expansive than New York City, which seemed untowardly cramped in comparison. Yet, the sheer size of the Forbidden City and the Palace Museum was not what caught my eye most. Instead, it was the small number of precious artifacts in the museum. The number of precious artifacts was so low that I actually voiced my disappointment to my buddy Zhu Jun. In courtyard after courtyard, I expected to see precious jade and gold statuettes, but every time, I only saw mammoth stone walls and wooden beams. Yet, when I left the Forbidden City at about 4:00 PM, I remembered that most of the precious artifacts had been taken to Taiwan during the Chinese Civil War of 1949. As I left the museum, I sighed and noted that the lack of artifacts was the product of a conflict that has remain unresolved for 59 years.</p>
          </li>
          <li class="comment_odd">
            <div class="submitdate"><a href="#">Monday, August 4, 2008</a></div>
            <p>This morning, we rode a small van to the Mutianyu (慕田峪) section of the Great Wall. While riding in the van for a bit over an hour, I noticed the thick gray haze in the distance. At first, I thought it was smog, but after further inspection, I realized that it was actually a thick mist that had accumulated from the lack of wind. At the same time, I noticed that the roads that were very “Western-looking” with a gray divider and white shoulder lines, and I noted that if you took away all the road signs, then you might really think that this was somewhere in the Western part of the United States. Yet, I soon realized that my assertion revealed a pro-Western mentality in me, in that I attributed &quot;Western-looking&quot; with &quot;modern&quot;. In retrospect, I should have simply called the roads &quot;modern&quot;.

			As expected, the Mutianyu section was a grand display of human achievement. To describe it simply as a huge brick wall with steep stairs would be an insult to its grandeur, and yet, on the flip side, that description would be entirely accurate. After purchasing tickets and venturing past the street peddlers that sold fruits and herbs, we climbed a few hundred steps up to the wall. There, we took photographs like any tourist and continued climbing until we reached the end of the section. At the end of the section, we were greeted by thick weeds and a sign that told us not to proceed as further. We rested there and walked back to where we came. Afterwards, we went to Hong Luosi (紅螺寺), a famous Buddhist temple in Beijing, and saw a graceful pond with a waterfall that was lined with small pebbles. In addition, Zhu Jun, Winnie Tong, and I saw several Buddhist temples (殿 – dian4 to be accurate) that honored different bodhisattvas. We climbed over a thousand steps up to the Guanyin si (觀音寺), which was far more tiring that I expected. I attributed my tiredness to the ascent’s design: Every time I thought I was done with stairs, I saw another flight of stairs. Fortunately, we took a slide (滑道) down the mountain, which was fun because the speed of each of the luges was controlled by the rider and not by some centralized machine. The day concluded with a meal at a Thai restaurant called Banana Leaf, which was okay but somewhat disappointing in light of the restaurant’s relatively high prices.</p>
          </li>
          <li class="comment_even">
            <div class="submitdate"><a href="#">Tuesday, August 5, 2008</a></div>
            <p>Today was a lighter day. We went to a Starbucks outside of Tsinghua University in Haidian District, and there I saw the high prices (about 30 RMB for a mocha/frappuchino), which is similar to the prices in the US. I also noticed that there were relatively few Chinese in the coffee shop; most were American and European expatriates using the shop’s wireless Internet. However, as I was browsing the shop’s collection of moon cakes, I realized that in the few days since coming to China, I had become uncommonly “stingy”. On things that cost $3.00 in the United States, it was common practice to spend at most 5 RMB (equivalent to $0.75) in China. As a result, when that item was listed as 20 RMB in China, the common response, even for wealthy Americans, was to haggle or to walk off. I realized then how paradoxical this reversal in attitude was: why should Americans balk at prices they are accustomed to, just because they are in China?
			<br><br>
			After my realization, we had a practice discussion in the Starbucks with our Chinese counterparts: Wang Ruoying, a Tsinghua University student, Li Jia, a Beijing University student, Lu Lu, a native Beijing resident now studying in the United States, and Shen Chen, a high school student at Beijing No. 4 High School. In our discussion, we touched on several issues, most importantly, the misconceptions that Westerners have about China. We concluded fairly uniformly that many Westerners think that the Chinese are a monolithic bloc when they are, in fact, not. Several of us also concluded that many Westerners only wish for China to remain its old, pre-modern self. For whatever reason, the discussion eventually turned into a discussion about what it meant to be “Chinese” and about national identity. In one instance, after Winnie Tong said that she felt more Chinese than American, Wang Ruoying said that in her eyes, Winnie was just a typical Chinese-American (more American than Chinese). In the same discussion, I was asked for my views on Taiwan. I told them that I believed that the people of Taiwan should have their say on the issue, and I asked my Chinese counterparts why they felt the need to unite Taiwan at all costs. They responded that if Taiwan were to become independent, then China would split into pieces.
			<br><br>
			After our practice discussion, we went to Xiushui Jie (秀水街) for a pleasant stroll around a park and saw several embassies (Colombia, Finland, Britain, and Vietnam). While in the park, Jae, Alex, and Evan played ping-pong with a middle-aged man and woman and discovered, pursuant to the American stereotype, that the two were quite good. Then we ate majiang mian (麻醬麵) in a local restaurant before proceeding to the Plato Teahouse in Haidian District. There, we engaged in another discussion, which was a little more rowdy and somewhat more unfocussed than the one in the morning. Among the questions asked included “Is the ‘American dream’ really as achievable as Americans imagine?”, “Should the rest of the world follow the American/Western way of government?”, and “Are Americans hypocritical to criticize China for its human rights violations?” We didn’t arrive at an answer for any of the above questions, but I did leave with a better understanding of the Chinese ethos. Like Americans, the Chinese are proud of themselves, and they will not allow others to criticize them indiscriminately. That may seem obvious, but many Americans, in my opinion, forget that and treat the Chinese as a “second-rate” people while expecting the Chinese to embrace them as “carriers of the Light”.
			<br><br>
			That night, my host family invited me to dinner at Quan Jude (全聚德), a famous restaurant, and the highlight of the evening was the most succulent Peking duck that I ever had.</p>
          </li>	
		  <li class="comment_odd">
			<div class="submitdate"><a href="#">Wednesday, August 6, 2008</a></div>
			<p>This morning, we met at 9:00 AM at the Starbucks outside Tsinghua University where we had a short discussion about the difference between Chinese and American educational systems. We decided that Chinese students memorize more than American students, and that American students have more freedom to do as they please. The Chinese students uniformly criticized the Chinese educational system for being too “stressful”, while the American students (me included) noted that the American educational system is probably too relaxed.
			<br><br>
			Afterwards, our Chinese counterparts gave us a short tour of Tsinghua University, considered by many to be the best university in China. We walked by the Soviet-style administrative buildings (tall and imposing yet bland overall) before venturing to the more modern-looking academic buildings. We paid a visit to the library and saw hundreds of Tsinghua University students busy studying vocabulary words for the GRE. Interestingly enough, many of them used the same book, which was also, by the way, the book used by my buddy Zhu Jun. For the most part, the university library was fairly standard, with rows and rows of books and manuscripts untouched and slowly rotting away. There were several German publications that had not been touched in ages, and there was one particularly interesting American publication that was dedicated to predicting the future. It predicted that in this decade, there would be more partisanship and more bitter and false attacks during presidential elections. I thought of John Kerry, whom Republicans “swift-boated” in 2004, and thought that the predictions were unexpectedly accurate. However, Evan noted that their predictions were fairly obvious. I nodded and thought of Rasputin, whom some claimed in the aftermath of 9/11 to have predicted 9/11, when all he did was write a few gloomy statements that could be applied to any number of events.
			<br><br>
			The rest of the day was free-time, and I caught up on some sleep while watching a Chinese female weightlifter break the world record five times in a single weightlifting session.</p>
		  </li>		  
		  <li class="comment_even">
			<div class="submitdate"><a href="#">Thursday, August 7, 2008</a></div>
			<p>This morning, we visited the headquarters of BOCOG, the Beijing Organizing Committee for the Olympic Games. It was a large modern skyscraper with glass curtain-walls, and outside of it were several guard booths and a large Omega clock that said that the Olympics were only a day and ten hours away. On the third floor, the BOCOG director in charge of volunteer operations greeted us and gave each of us five wristbands, each of whose colors represented a different continent. I thanked him for welcoming us in typical Chinese fashion, and the director talked about how great it was for us American students to visit China. He wished us for return in the future and to contribute to building better Sino-American relations; it was a good speech and free of the bureaucratic clichés that are common in such speeches. Afterwards, we gave him a gift and went back downstairs to purchase fuwa’s, which were on-sale for a change.
			<br><br>
			We had a short lunch at a restaurant that served Shanghainese food before arriving at the Beijing Resource Hotel outside of Peking University for our panel discussion. We waited for about an hour before forty or so well-dressed Peking University and Tsinghua University students arrived. The attendees seemed uniformly interested in Sino-American relations, and they all spoke English quite well. The panel discussion began at a little past 3:00 PM, and the discussion focused mainly on China’s economic rise. Many comments (mine included) included references to China’s booming economy, to its grand buildings, and into its ascent onto the world stage. I mentioned that China’s rise scared many Americans because Americans don’t quite understand why or how a Communist country can thrive. The audience members laughed when they heard my comments, and I imagine that they think that Americans have been brainwashed into believing that a democracy is the only legitimate form of government.
			<br><br>
			Several other comments focused on the fusion of Chinese and Western culture. Though China has thousands of McDonald’s and Starbucks, China is not and will not be another America, the other panelists said. Li Jia, in particular, noted that although China has embraced American businesses, it has not really welcomed American culture, much less American-style republicanism. Superficially, the Chinese may wear the same clothes or watch the same television shows (like <em>Prison Break</em>), but in reality, the Chinese still believe in the Confucianist virtues of filial piety and unerring respect for elders and leaders. Their unerring respect for leaders may, in part, explain why they react so strongly when Americans criticize their form of government.
			<br><br>
			At the end of the panel discussion, I talked to one Peking University student, who claimed that he was a devout conservative Christian, which is unusual in China. Earlier, the student had claimed that he favored democracy but said that it would take time for China to become a full democracy. As his remark was somewhat different from the rest of the comments, I asked him for clarification. He explained that Peking University students are typically more “open” to Western thought than are Tsinghua University students. He also said that most of the Tiananmen Square protestors were Peking University students, so it was not unusual for him to espouse such views. In any case, he was careful to imply that he did not oppose the government because the government had given food, clothing, and wealth to him and his compatriots. Overall, I concluded that the overall range of comments was far narrower than would be expected in the United States; all of the students expressed relatively conservative pro-Communist Party views, and not a single student criticized the government. In fact, the students spent most of their time criticizing the United States government or the misconceptions that Westerners have about China. To others, this narrowness might not be very surprising, but to me, it was utterly surprising that forty of the best students in China could all have the same views.
			<br><br>
			That night, after dinner at a Sichuanese restaurant, we went to a karaoke bar to relax. Sitting in the lobby, I found myself almost brought to tears just listening to the Chinese pop music blaring in the lobby and thinking about how important the Olympics were to China. I told Alex that, in many ways, the Beijing Olympics would prove that the Chinese race was not inferior to any other race and that the Chinese people would forever remember the day in which the world saw China’s glory. My comments were undoubtedly nationalistic and perhaps even a bit insecure, but they did represent my thoughts at the time.
			<br><br>
			Fortunately for me, the night ended on a much more uplifting note. After I had sung a few Jolin Tsai songs out-of-tune and off-tempo, Alvin Huang, the IMUSE founder, informed us that he had obtained six tickets to the opening ceremony. Previously, we had been told that we would be unable to attend the opening ceremonies in person, and so, it was a delightful shock to discover that we would be able to have prime seats at one of the most important Olympic events in history. As one might expect, the rest of the night was blissful.</p>
		  </li>
		  <li class="comment_odd">
			<div class="submitdate"><a href="#">Friday, August 8, 2008</a></div>
			<p>'My host mother graciously prepared a full lunch for me today, which was unusual because she normally never cooks. As a main dish, she cooked a chicken using Coca-Cola as seasoning; though that initially struck me as strange, the dish tasted good nonetheless. In fact, it far exceeded my expectations and made me realize that Coca-Cola was a venerable seasoning agent.
			<br><br>
			At 2:00 PM, our big day began. I left for the Wudaokao (五道口) Station right outside my host family’s residence, and there, I met up with Evan, Li Jia, and the three other fellowship members. We took line 13 and transferred to line 10 at the Zhichunlu Station before disembarking at the Beitucheng Station. At the Beitucheng Station, thousands of Chinese disembarked the subway train and went up to the street to go through security. We arrived early, and we waited for around forty minutes before the security guards searched us. The guards were slow but methodical, and they asked me to remove the contents of my pockets for them to see. Without a doubt, it was obvious that the guards would bear significant responsibility if a protestor or terrorist were to pass through.
			<br><br>
			At around 4:00 PM, we entered the Olympic Green, which was a vast area of finely manicured lawns and impressively-designed buildings meant to convince tourists to buy Omega watches or CNPC gas. We entered the Omega building and saw watches costing 80,000 RMB, or about twice the average household income in Beijing. Nevertheless, I saw a fair number of well-dressed Chinese tourists that looked to be able and willing to purchase luxury watches. After our window-shopping, we decided to engage in further window-shopping by venturing over to the National Aquatic Stadium, which was also known as the Water Cube. The water cube was brilliantly pioneering; in theory, it was little more than a cubic structure with membranes that resembled water droplets on its five sides. Yet, in person, it was so striking in that it actually looked like a water cube, a purpose-built structure meant to help the world’s best swimmers demolish world records. Unfortunately, because we had no tickets to the aquatic events, standing outside of the Water Cube was as close as we could get.
			<br><br>
			At around 6:00 PM, after wandering about the Olympic Green for a little more than an hour, we entered the Bird’s Nest. On television, the Bird’s Nest was a marvel to behold, but in person, it was even more impressive. The steel girders spiraling about the structure in seemingly random ways were so beautifully innovative that it made other stadiums look woefully antiquated. Yet, once in the Bird’s Nest, I discovered that the interior was no different from any other large-scale stadium, which was logical but somewhat disappointing. Still, the stadium’s atmosphere was unlike anything I had ever seen. Even though it was still early, the thousands of spectators in the stadium produced a cheer that was so loud and uniform that it gave me shivers, not because I was scared or intimated but because I was shocked to see that thousands of people could chant the same thing or stomp at the same time.
			<br><br>
			As expected, the opening ceremonies of the 29th Olympiad began with a boom. 2,008 drummers pounded their drums, and their drums lit up with incredible synchronicity to display the countdown to 8:08 PM. I loved every moment of the opening ceremonies, including the scene where Sarah Brightman and Liu Huan stand on top of the Earth and sing the Olympic theme song. While Liu Huan’s singing was less than perfect, the entire scene was so beautiful that it more than compensated for Liu Huan’s over-excitement. Especially when the children’s faces were placed by the globe, the scene showed how all the world’s people are the same. In a way, the scene showed how “one world” does share “one dream”: the dream that the world’s children will be better than their parents.
			<br><br>
			The night ended with Li Ning “running” around the stadium before lighting the Olympic cauldron in a brilliant display of choreography. When the ceremonies ended, I thought to myself, “The Chinese people don’t want to be like the West. They want to be better than the West, and tonight, they have shown that it is possible.”After a tiring but exciting night, we slept in today. In the afternoon, we went to the Houhai (後海) district of Beijing with its collection of restored hutongs (little city villages with long alleys and small gates). Among other things, I bought a seal carving and had it engraved with my Chinese name in seal script. I was pleased with the carver’s focus and attention to detail, but I was less than thrilled with the intense bargaining that the other fellowship members engaged in. They wanted the carver to cut the price in half, and when the carver did not budge enough, they continued to push him until he finally relented. To me, this seemed unnecessary because our bargaining only saved us 40 RMB (about $7.00). 40 RMB, to us, is nothing, but it is enough for him to treat his family to a nice meal.  Nevertheless, I stood by idly and did nothing, so I suppose I must bear some of the blame for depriving this industrious carver of 40 RMB.
			</p>
		  </li>
		  <li class="comment_even">
			<div class="submitdate"><a href="#">Saturday, August 9, 2008</a></div>
			<p>After a tiring but exciting night, we slept in today. In the afternoon, we went to the Houhai (後海) district of Beijing with its collection of restored hutongs (little city villages with long alleys and small gates). Among other things, I bought a seal carving and had it engraved with my Chinese name in seal script. I was pleased with the carver’s focus and attention to detail, but I was less than thrilled with the intense bargaining that the other fellowship members engaged in. They wanted the carver to cut the price in half, and when the carver did not budge enough, they continued to push him until he finally relented. To me, this seemed unnecessary because our bargaining only saved us 40 RMB (about $7.00). 40 RMB, to us, is nothing, but it is enough for him to treat his family to a nice meal.  Nevertheless, I stood by idly and did nothing, so I suppose I must bear some of the blame for depriving this industrious carver of 40 RMB.
			<br><br>
			That night, although we passed by numerous nightclubs and bars, I went home without drinking a single sip of alcohol.</p>
		  </li>
		  <li class="comment_odd">
			<div class="submitdate"><a href="#">Sunday, August 10, 2008</a></div>
			<p>Today, we originally set out to visit Yonghe Gong (雍和宮), a Buddhist lama temple. However, we happily canceled our plans when we saw that the women’s road cycling competition would run right through the Yonghe Gong area. Evidently, we were not the only ones to do so because we saw thousands of Chinese and Western tourists standing by the road hoping to catch a glimpse of the cyclists. Professional photographers also stood by with their high-end DSLRS ready to catch a shot, and as the cyclists rode closer to our area, swarms of police cars drove through to ensure that the roads were clear. Then, in a matter of seconds, the cyclists breezed through our area, and although my camera clicked, I discovered that my pictures were all uniformly blurry because I had not expected the cyclists to pass us so quickly. Yet, without a doubt, the experience was memorable because this was the first time that I had ever witnessed a cycling competition in-person.
			<br><br>
			That afternoon, we went through the same security checks that we had gone through two days earlier in order to enter the Olympic Green, but for some reason, the guards seemed to be faster this time around. After waiting for only twenty minutes, we arrived at the Beijing National Indoor Stadium with our women’s gymnastics tickets in hand. Though they were only tickets for a qualifying competition, we had plenty of fun watching the diminutive gymnasts somersault through the air in seemingly impossible ways. Even though Evan, Kelly, and I were not gymnasts, we had fun guessing the scores on the balance beam and were delighted to discover that, more times than not, we were accurate to within 0.1 points.
			<br><br>
			That night, after leaving from the Olympic Green, I had a short dinner with Tracy Li at a fast-food noodle restaurant, which was amusing because the restaurant was allegedly founded by a Chinese-American living in California. That trivia note aside, the rain that night was devastating, and many of the streets around Wudaokao Station were flooded.</p>
		  </li>
		  <li class="comment_even">
			<div class="submitdate"><a href="#">Monday, August 11, 2008</a></div>
			<p>Today, we had a lecture by Professor Peng Xiaoyu, a history professor at Peking University. I went in thinking that Professor Peng was going to be the stereotypical Chinese professor, who would say that all Chinese were good and that all Westerners were bad, and that Chinese-Americans should choose sides.
			<br><br>
			Fortunately for me, I was quickly proven wrong. In fact, Professor Peng did not really talk about Sino-American relations. He instead spent most of his time talking about the history of Peking University and about how Peking University did not have a classics department or an American/European History department. He told us that the only department that resembled an American/European History department was a “world history” sub-department in the History department, and he reminded us that the “world history” sub-department only constituted a third of the entire History department. In his mind, that was absolutely flabbergasting. Professor Peng believed that if China wished to become a world power, then it would need to learn about the history and culture of other world powers. He ended his lecture by encouraging all of the Tsinghua and Peking University students in attendance to take classes on American and European history, anything non-Chinese. Then, in a strange move, he asked us to encourage Peking University’s administration to provide more financial aid to his department. We applauded and asked him a few questions before the students in attendance broke up into little groups to discuss the issues further.
			<br><br>
			I found myself talking to Wang Ruoying and two other Tsinghua University students. I mentioned that the Chinese political and law-enforcement systems are so opaque that nobody really knows what goes on in Zhongnanhai, China’s Capitol Hill. They responded that it was not opaque in that the government did periodically release information on criminals and subversives. I responded that the information released is, without exception, exceptionally limited because there is only “one voice”: the government’s voice. They accepted that this was true but not before criticizing America’s media for being exceedingly biased, giving me the impression that, at least to this group of students, the government’s voice was better than the voice of ‘biased’ media outlets. Then, I mentioned that China subscribed to torturing alleged criminals, separatists, and terrorists, and to this, the students murmured that it was true. In my eyes, it seemed that the Chinese students acknowledged certain contentious government actions and grudgingly sanctioned them only because they felt it was in the nation’s best interests and not because they personally agreed with them. Still, what surprised me a little was that the students felt the need to implicitly defend the government, even when it was obvious that they disagreed with torturing alleged criminals.
			<br><br>
			To digress a little, one sour note during the lecture was Professor Peng’s criticism of HuShi (胡適), a Chinese intellectual from the early 20th century. Having studied the works and accomplishments of HuShi earlier this year, I was stunned that Professor Peng strongly criticized him for not teaching the Chinese about Western thought. After all, in my mind, HuShi was, first and foremost, a pragmatist, who believed in visiting remote Chinese villages, in studying their problems intimately, and in solving their problems case-by-case (實地考察, shi2di4 kao3cha2, as he used to say). To him, teaching Chinese about Western thought would be like teaching Latin to illiterate Chinese. Interesting but irrelevant. Thus, I believe that Professor Peng and HuShi have a difference of opinion and philosophy, but that is certainly no reason for Professor Peng to attack HuShi so fiercely. In my opinion, Professor Peng should simply disagree respectfully.
			<br><br>
			While in my host family’s home that night, I watched an interesting video on msnbc.com about the new American dream. The video talked about Chinese-Americans trying to further their careers in China, while at the same time, connecting with their “Chinese side”. The video also described how the interaction was two-way in that the Chinese-Americans also brought their Western thought with them to China. While watching the video, I was reminded that Winnie Tong had said to me time and time again that she wished to live in China after graduating from college in the United States, and I realized then that Winnie Tong’s desire was certainly not an anomaly.</p>
		  </li>
		  <li class="comment_odd">
			<div class="submitdate"><a href="#">Tuesday, August 12, 2008</a></div>
			<p>This morning, we took a taxi to the 798 Art District after meeting at the Sanyuanqiao subway station at 9:30 AM. At the 798 Art District, we saw many exhibitions, including one that featured a stuffed dog, which was somewhat disgusting. The other exhibitions were more forgettable, primarily because they seemed highly derivative. Yet, several pieces of art stood out. At first glance, one painting appeared to be typical Socialist propaganda because it featured several Mao-suit-wearing men waving Mao’s Little Red Book while rowing a boat across an uncertain sea. Yet, on second glance, I realized that some of the men held watercolor brushes in their hands and that, unlike the other men, they were painted in yellow and not in red. Red is considered the color of Communism, and yellow is the color of the Chinese race. As a result, I inferred that the painting was trying to highlight the conflict between “old China”, the men painted in yellow holding watercolor brushes, and “new China”, the Communist supporters painted in red holding Mao’s Little Red Book. I explained this to Wang Ruoying, and she seemed surprised that so much could be made out of a single painting. I told her that my interpretation was just one of many and that hundreds of other interpretations were also valid.
			<br><br>
			The second piece was a red figurine of a Laughing Buddha that wore a Mao suit. It was as incongruous as the painting but far less subtle. By the figurine’s outfit, the figurine seemed to suggest that it was possible to be a Buddhist Communist, but on second glance, the figurine seemed to suggest that it was laughable to suggest that Buddhism was compatible with Communism. In fact, the figurine seemed to suggest that the concept was so laughable that it deserved a rebuke.
			<br><br>
			Regardless of the figurine’s message, the two pieces of art made me feel that modern China is, in many ways, at a crossroads between its historical past (Buddhism, Confucianism, Chinese brush painting, etc.) and its immediate past (Chairman Mao, Communism, socialism, etc.). However, in my opinion, this does not mean that China will forget either of its pasts and wholeheartedly embrace one of them. Instead, just like these works of arts, I believe that China will embrace a hybrid of its pasts, i.e. socialism with Confucianist elements and simultaneous veneration of Chairman Mao and Confucius. Although both men would probably be appalled to discover that they could be mentioned together, I feel that this is what the Chinese will do for the foreseeable future.
			<br><br>
			The evening concluded with a visit to the Olympic Field Hockey Green, where we watched the Chinese women’s field hockey team obliterate South Africa, 3-0. Because the victor was not in doubt about thirty minutes in, the highlight of the night was watching the nationalistic Chinese spectators roar after each goal. In accordance with Chinese government recommendations, the spectators did not accurse South Africa or shout politically-insensitive lines. Instead, the spectators stuck with the “Zhong1guo2, jia1you2 中國加油!” line, which got pretty boring after about twenty minutes. In a way, I wish the Chinese spectators had done what Americans do during baseball games, i.e. buy a Beer and relax.</p>
		  <li class="comment_even">
			<div class="submitdate"><a href="#">Wednesday, August 13, 2008</a></div>
			<p>Today was a free day, and I went to the Tiantan Park (天壇 – Temple of Heaven) with my uncle in Beijing. I discovered that, like Tiananmen Square, Tiantan was a massive park several thousand acres in areas and that, like Central Park in New York City, it was a communal park where residents gathered to sing Beijing operas, ribbon dance, and practice taichi. However, the highlight of the day was our visit to the Qinian Dian (祈年殿), where Ming and Qing emperors used to gather to pray for good luck each year. The structure, with its sloping blue tiled roof and red walls, was built without any nails, and yet, it is still standing after six hundred years. Perhaps, that is the lasting message of this visit: Though China may have been battered hundreds of times in the past, China is alive and well today, and with luck, it will remain that way for another six hundred years.</p>
		  </li>		  
		</ul>
      </div>
 </div>
 
	<script type="text/javascript">
	
	function toggle(id) 
	{
	var toggle = document.getElementById(id);
	
	
	if(toggle.style.display=='')
	{
		toggle.style.display ='none';
		toggle.class = '';
	}
	else
	{
		toggle.style.display='';
		toggle.class = 'active';
	}
	}
	</script>
	
<? $sub = 'blogs'; $blog = 'eric'; include 'columnav.php'; ?>
    <div class="clear"></div> 
	</div>
</div>

<? include 'footer.php' ?>
